name: "Workflow Setup"

description: "Common setup across multiple workflows."

inputs:
  google_services_json:
    description: 'File content for google-services.json'
    required: true
  google_services_plist:
    description: 'File content for GoogleService-Info.plist'
    required: true

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set Up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version-file: .github/.java-version

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        # Only write to the cache for builds on the 'development' branch
        cache-read-only: ${{ github.ref != 'refs/heads/development' }}

    - name: Recreate google-services.json
      shell: bash
      env:
        GOOGLE_SERVICES_SECRET: ${{ inputs.google_services_json }}
      run: |
        echo "$GOOGLE_SERVICES_SECRET" > ./androidApp/google-services.json

    - name: Recreate GoogleService-Info.plist
      shell: bash
      env:
        GOOGLE_SERVICES_SECRET: ${{ inputs.google_services_plist }}
      run: |
        echo "$GOOGLE_SERVICES_SECRET" > ./iosApp/mclooRecipesIOS/GoogleService-Info.plist