name: Desktop Build

# This will cancel any in progress workflows for the same PR, if
# multiple pushes happen in quick succession.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on: pull_request

jobs:
  android-build:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/workflow_setup
        with:
          google_services_json: ${{ secrets.GOOGLE_SERVICES_JSON }}
          google_services_plist: ${{ secrets.GOOGLE_SERVICES_PLIST }}

      - name: Recreate google-services.json
        env:
          GOOGLE_SERVICES_SECRET: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_SECRET" > ./androidApp/google-services.json

      - name: Build Project
        run: ./gradlew :desktopApp:build
